steps:
  # Docker Build app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/empapp', '-f', 'Dockerfile.web', '.']

  # Docker Push app img
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/empapp']
  
    # Docker Build db
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/cloudsqlauth', '-f', 'Dockerfile.db', '.']
          
  # Docker Push db img
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/cloudsqlauth']

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s-deployment.yaml
      - --location=us-central1
      - --cluster=my-gke-cluster

options:
  logging: CLOUD_LOGGING_ONLY