---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "emp-deployment"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "deployment-1"
  namespace: "emp-deployment"
  labels:
    app: "empapp"
    db: "cloudsql"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "empapp"
      db: "cloudsql"
  template:
    metadata:
      labels:
        app: "empapp"
        db: "cloudsql"
    spec:
      containers:
      - name: "empapp-sha256-1"
        image: "us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/empapp:latest"
      - name: "cloudsqlauth-sha256-2"
        image: "us-central1-docker.pkg.dev/gcp-devops-436118/employee-repository/cloudsqlauth:latest"

apiVersion: "v1"
kind: "Service"
metadata:
  name: "deployment-1-service"
  namespace: "emp-deployment"
  labels:
    app: "empapp"
    db: "cloudsql"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "empapp"
    db: "cloudsql"
  type: "NodePort"
